In [1]:
import numpy as np

In [2]:
np.array([1,2,3])   # one dimensional array

array([1, 2, 3])

In [3]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.full((2,3), fill_value=7)

array([[7, 7, 7],
       [7, 7, 7]])

In [9]:
np.empty((2,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        4.00530950e-307],
       [2.67014974e-306, 1.42413555e-306, 1.78019082e-306,
        1.37959740e-306]])

In [10]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0, np.pi, 5)  # Evenly spaced range with 5 elements

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [13]:
np.random.random((3,4))          # Elements are uniformly distributed from half-open interval [0.0,1.0)

array([[0.416681  , 0.03033418, 0.85047356, 0.69173796],
       [0.05712428, 0.7267664 , 0.47977168, 0.16980349],
       [0.6917932 , 0.30466285, 0.68006619, 0.51989499]])

In [14]:
np.random.normal(0, 1, (3,4))    # Elements are normally distributed with mean 0 and standard deviation 1

array([[-0.59884003,  1.04513973, -1.54714933, -0.17659387],
       [ 0.42562835, -0.1297255 ,  1.0291401 , -1.36940553],
       [-2.00673162,  0.06423799,  1.01404371, -1.95586565]])

In [15]:
np.random.randint(-2, 10, (3,4))  # Elements are uniformly distributed integers from the half-open interval [-2,10)

array([[ 5,  1, -2,  5],
       [ 5, -1,  7, -1],
       [ 7,  8,  3, -1]])

In [16]:
np.random.seed(0)
print(np.random.randint(0, 100, 10))
print(np.random.normal(0, 1, 10))

[44 47 64 67 67  9 83 21 36 87]
[ 1.26611853 -0.50587654  2.54520078  1.08081191  0.48431215  0.57914048
 -0.18158257  1.41020463 -0.37447169  0.27519832]


In [17]:
new_generator = np.random.RandomState(seed=123)  # RandomState is a class, so we give the seed to its constructor
new_generator.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [18]:
def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")
    print(a)

In [19]:
b=np.array([[1,2,3], [4,5,6]])
info("b", b)

b has dim 2, shape (2, 3), size 6, and dtype int32:
[[1 2 3]
 [4 5 6]]


In [20]:
c=np.array([b, b])          # Creates a 3-dimensional array
info("c", c)

c has dim 3, shape (2, 2, 3), size 12, and dtype int32:
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [21]:
d=np.array([[1,2,3,4]])                # a row vector
info("d", d)

d has dim 2, shape (1, 4), size 4, and dtype int32:
[[1 2 3 4]]


In [22]:
a=np.array([1,4,2,7,9,5])
print(a[1])
print(a[-2])

4
9


In [23]:
b=np.array([[1,2,3], [4,5,6]])
print(b)
print(b[1,2])    # row index 1, column index 2
print(b[0,-1])   # row index 0, column index -1

[[1 2 3]
 [4 5 6]]
6
3


In [24]:
# As with lists, modification through indexing is possible
b[0,0] = 10
print(b)

[[10  2  3]
 [ 4  5  6]]


In [25]:
print(b[0])    # First row
print(b[1])    # Second row

[10  2  3]
[4 5 6]


In [26]:
print(a)
print(a[1:3])
print(a[::-1])    # Reverses the array

[1 4 2 7 9 5]
[4 2]
[5 9 7 2 4 1]


In [27]:
print(b)
print(b[:,0])
print(b[0,:])
print(b[:,1:])

[[10  2  3]
 [ 4  5  6]]
[10  4]
[10  2  3]
[[2 3]
 [5 6]]


In [28]:
b[:,1:] = 7
print(b)

[[10  7  7]
 [ 4  7  7]]


In [29]:
print(b[:,0])    # First column
print(b[1,:])    # Second row

[10  4]
[4 7 7]


In [30]:
a=np.arange(9)
anew=a.reshape(3,3)
info("anew", anew)
info("a", a)

anew has dim 2, shape (3, 3), size 9, and dtype int32:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
a has dim 1, shape (9,), size 9, and dtype int32:
[0 1 2 3 4 5 6 7 8]


In [31]:
d=np.arange(4)             # 1d array
dr=d.reshape(1,4)          # row vector
dc=d.reshape(4,1)          # column vector
info("d", d)
info("dr", dr)
info("dc", dc)

d has dim 1, shape (4,), size 4, and dtype int32:
[0 1 2 3]
dr has dim 2, shape (1, 4), size 4, and dtype int32:
[[0 1 2 3]]
dc has dim 2, shape (4, 1), size 4, and dtype int32:
[[0]
 [1]
 [2]
 [3]]


In [32]:
info("d", d)
info("drow", d[:, np.newaxis])
info("drow", d[np.newaxis, :])
info("dcol", d[:, np.newaxis])

d has dim 1, shape (4,), size 4, and dtype int32:
[0 1 2 3]
drow has dim 2, shape (4, 1), size 4, and dtype int32:
[[0]
 [1]
 [2]
 [3]]
drow has dim 2, shape (1, 4), size 4, and dtype int32:
[[0 1 2 3]]
dcol has dim 2, shape (4, 1), size 4, and dtype int32:
[[0]
 [1]
 [2]
 [3]]


In [33]:
a=np.arange(2)
b=np.arange(2,5)
print(f"a has shape {a.shape}: {a}")
print(f"b has shape {b.shape}: {b}")
np.concatenate((a,b))  # concatenating 1d arrays

a has shape (2,): [0 1]
b has shape (3,): [2 3 4]


array([0, 1, 2, 3, 4])

In [34]:
c=np.arange(1,5).reshape(2,2)
print(f"c has shape {c.shape}:", c, sep="\n")
np.concatenate((c,c))   # concatenating 2d arrays

c has shape (2, 2):
[[1 2]
 [3 4]]


array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [35]:
np.concatenate((c,c), axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [36]:
print("New row:")
print(np.concatenate((c,a.reshape(1,2))))
print("New column:")
print(np.concatenate((c,a.reshape(2,1)), axis=1))

New row:
[[1 2]
 [3 4]
 [0 1]]
New column:
[[1 2 0]
 [3 4 1]]


In [37]:
np.stack((b,b))

array([[2, 3, 4],
       [2, 3, 4]])

In [38]:
np.stack((b,b), axis=1)

array([[2, 2],
       [3, 3],
       [4, 4]])

In [39]:
d=np.arange(12).reshape(6,2)
print("d:")
print(d)
d1,d2 = np.split(d, 2)
print("d1:")
print(d1)
print("d2:")
print(d2)

d:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
d1:
[[0 1]
 [2 3]
 [4 5]]
d2:
[[ 6  7]
 [ 8  9]
 [10 11]]


In [40]:
d=np.arange(12).reshape(2,6)
print("d:")
print(d)
parts=np.split(d, (2,3,5), axis=1)
for i, p in enumerate(parts):
    print("part %i:" % i)
    print(p)

d:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
part 0:
[[0 1]
 [6 7]]
part 1:
[[2]
 [8]]
part 2:
[[ 3  4]
 [ 9 10]]
part 3:
[[ 5]
 [11]]


In [41]:
L=[1, 5.2, "ab"]
L2=[]
for x in L:
    L2.append(x*2)
print(L2)

[2, 10.4, 'abab']


In [42]:
a=np.array([2.1, 5.0, 17.2])
a2=a*2
print(a2)

[ 4.2 10.  34.4]


In [43]:
b=np.array([-1, 3.2, 2.4])
print(-a**2 * b)

[   4.41   -80.    -710.016]


In [44]:
print(np.abs(b))
print(np.cos(b))
print(np.exp(b))
print(np.log2(np.abs(b)))

[1.  3.2 2.4]
[ 0.54030231 -0.99829478 -0.73739372]
[ 0.36787944 24.5325302  11.02317638]
[0.         1.67807191 1.26303441]


In [45]:
np.random.seed(0)
a=np.random.randint(-100, 100, (4,5))
print(a)
print(f"Minimum: {a.min()}, maximum: {a.max()}")
print(f"Sum: {a.sum()}")
print(f"Mean: {a.mean()}, standard deviation: {a.std()}")

[[ 72 -53  17  92 -33]
 [ 95   3 -91 -79 -64]
 [-13 -30 -12  40 -42]
 [ 93 -61 -13  74 -12]]
Minimum: -91, maximum: 95
Sum: -17
Mean: -0.85, standard deviation: 58.39886557117355


In [46]:
np.random.seed(9)
b=np.random.randint(0, 10, (3,4))
print(b)
print("Column sums:", b.sum(axis=0))
print("Row sums:", b.sum(axis=1))

[[5 6 8 6]
 [1 6 4 8]
 [1 8 5 1]]
Column sums: [ 7 20 17 15]
Row sums: [25 19 15]


In [47]:
a=np.arange(1000)
%timeit np.sum(a)

2.71 µs ± 39.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [48]:
%timeit sum(a)

42.4 µs ± 1.11 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [49]:
np.arange(3) + np.array([4])

array([4, 5, 6])

In [50]:
np.arange(3) + 4

array([4, 5, 6])

In [51]:
a=np.full((3,3), 5)
b=np.arange(3)
print("a:", a, sep="\n")
print("b:", b)
print("a+b:", a+b, sep="\n")

a:
[[5 5 5]
 [5 5 5]
 [5 5 5]]
b: [0 1 2]
a+b:
[[5 6 7]
 [5 6 7]
 [5 6 7]]


In [52]:
np.array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [53]:
a=np.arange(3)
b=np.arange(3).reshape((3,1))
info("a", a)
info("b", b)
info("a+b", a+b)

a has dim 1, shape (3,), size 3, and dtype int32:
[0 1 2]
b has dim 2, shape (3, 1), size 3, and dtype int32:
[[0]
 [1]
 [2]]
a+b has dim 2, shape (3, 3), size 9, and dtype int32:
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [54]:
broadcasted_a, broadcasted_b = np.broadcast_arrays(a,b)
info("broadcasted_a", broadcasted_a)
info("broadcasted_b", broadcasted_b)

broadcasted_a has dim 2, shape (3, 3), size 9, and dtype int32:
[[0 1 2]
 [0 1 2]
 [0 1 2]]
broadcasted_b has dim 2, shape (3, 3), size 9, and dtype int32:
[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [55]:
a=np.array([1,2,3])
b=np.array([4,5])
try:
    a+b                 # This does not work since it violates the rule 3 above.
except ValueError as e:
    import sys
    print(e, file=sys.stderr)

operands could not be broadcast together with shapes (3,) (2,) 
